name: Backend image push

on:
  push:
    branches:
      - main  

jobs:
  call-image-push:
    uses: DavoA/reusable-workflows/.github/workflows/image-push.yaml@main
    with:
      image: app-front  
      context: ./backend
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
